const {test}=require('node:test');const assert=require('node:assert/strict');const {mkdtempSync,writeFileSync,rmSync,readFileSync}=require('node:fs');const {tmpdir}=require('node:os');const {join}=require('node:path');const {execFileSync}=require('node:child_process');const {generateKeyPairSync,randomUUID}=require('node:crypto');
const output=mkdtempSync(join(tmpdir(),'revomatix-test-'));writeFileSync(join(output,'package.json'),'{"type":"commonjs"}');
execFileSync('./node_modules/.bin/tsc',['--outDir',output,'--module','commonjs','--target','es2022','--moduleResolution','node','--skipLibCheck','--types','node','api/revomatix-submit.ts']);
process.on('exit',()=>rmSync(output,{recursive:true,force:true}));
const {validate,fields,mappedRow}=require(join(output,'server/revomatix/validation.js'));const handler=require(join(output,'api/revomatix-submit.js')).default;
const {voicePaths}=require(join(output,'src/voice/config.js'));
const body=()=>({submissionId:randomUUID(),name:'QA Test',email:'qa@example.com',company:'Synthetic QA',volume:'21–50',currentSpend:'Yes',currentUse:'Answering service',channelPreference:'Phone call',answer:'=SUM(1,2)',relatedIssues:[],anonymizedExamples:true,path:'/moving',landingPath:'/fitness',utmSource:'qa',utmMedium:'test',utmCampaign:'launch-check',utmContent:'form',utmTerm:'synthetic',referrer:'https://example.com/',test:true,startedAt:Date.now()-5000});
const call=async(b)=>{let code=200,result;const res={status(n){code=n;return this},json(v){result=v},setHeader(){},end(){}};await handler({method:'POST',body:b,headers:{host:'localhost','content-type':'application/json',origin:'http://localhost'}},res);return {code,...result}};
process.env.REVOMATIX_SHEET_ID='test-sheet';process.env.REVOMATIX_SHEET_TAB='QA';process.env.SUPABASE_URL='https://db.example';process.env.SUPABASE_SERVICE_ROLE_KEY='synthetic';process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL='test@example.com';process.env.GOOGLE_PRIVATE_KEY=generateKeyPairSync('rsa',{modulusLength:2048}).privateKey.export({type:'pkcs8',format:'pem'});
let rows,book,fail,ambiguous;const originalFetch=global.fetch;
function reset(){rows=[['Unrelated',...fields]];book=new Map();fail=false;ambiguous=false}
global.fetch=async(url,init={})=>{
 const data=init.body&&typeof init.body==='string'?JSON.parse(init.body):null;
 if(url.includes('oauth2'))return Response.json({access_token:'synthetic'});
 if(url.includes('/rpc/')){let r=book.get(data.p_id);if(r&&r.hash!==data.p_hash)return new Response('',{status:409});if(!r){r={hash:data.p_hash,row_number:Math.max(data.p_floor,book.size+2),created_at:'2026-09-14T10:00:00Z'};book.set(data.p_id,r)}return Response.json(r)}
 if(url.endsWith(':batchUpdate')){if(fail)return new Response('',{status:503});assert.equal(data.valueInputOption,'RAW');for(const d of data.data){const m=d.range.match(/!([A-Z]+)(\d+)/),col=[...m[1]].reduce((a,c)=>a*26+c.charCodeAt(0)-64,0)-1,row=Number(m[2])-1;rows[row]||=[];rows[row][col]=d.values[0][0]}if(ambiguous){ambiguous=false;throw new Error('Simulated lost response')}return Response.json({})}
 if(url.includes('sheets.googleapis')){const range=decodeURIComponent(url.split('/values/')[1]);const m=range.match(/!A(\d+):ZZ/);return Response.json({values:m?[rows[Number(m[1])-1]||[]]:rows})}
 throw new Error('Unexpected upstream')
};
test('all eleven routes derive correct niche and preserve attribution',()=>{for(const path of voicePaths){const lead=validate({...body(),path});assert.equal(lead.niche,path.slice(1));assert.equal(lead.landingPath,'/fitness');assert.equal(lead.test,true);assert.equal(lead.utmSource,'qa')}});
test('reject invalid input and honeypot',async()=>{for(const change of [{email:'bad'},{name:' '},{company:''},{path:'/unknown'},{website:'spam'},{submissionId:'bad'}])assert.equal((await call({...body(),...change})).code,400)});
test('accept optional qualification fields and validate niche-specific issues',()=>{const fitness=validate({...body(),path:'/fitness',relatedIssues:['Cancelled slots go unfilled','Failed membership payments']});assert.equal(fitness.relatedIssues,'Cancelled slots go unfilled | Failed membership payments');assert.equal(fitness.anonymizedExamples,true);assert.throws(()=>validate({...body(),volume:'Many'}),/Invalid form data/);assert.throws(()=>validate({...body(),path:'/moving',relatedIssues:['Cancelled slots go unfilled']}),/Invalid form data/)});
test('explicit header mapping refuses missing headers',()=>{assert.throws(()=>mappedRow(validate(body()),'now',['Email']),/SHEET_HEADERS/)});
test('confirmed RAW save, same-ID retry and concurrent retries use one row',async()=>{reset();const b=body();const first=await call(b);assert.equal(first.ok,true);assert.equal(rows[1][fields.indexOf('Original landing path')+1],'/fitness');assert.equal(rows[1][fields.indexOf('Optional answer')+1],'=SUM(1,2)');assert.equal(rows[1][fields.indexOf('Test traffic')+1],'true');assert.equal((await call(b)).duplicate,true);await Promise.all([call(b),call(b)]);assert.equal(rows.length,2);assert.equal(rows[1][0],undefined)});
test('ambiguous upstream save retries to same reserved row',async()=>{reset();const b=body();ambiguous=true;assert.equal((await call(b)).code,503);assert.equal((await call(b)).ok,true);assert.equal(rows.length,2)});
test('save failure never returns success and can be retried',async()=>{reset();const b=body();fail=true;assert.equal((await call(b)).code,503);assert.equal(rows.length,1);fail=false;assert.equal((await call(b)).ok,true);assert.equal(rows.length,2)});
test('existing leads and unrelated columns preserved',async()=>{reset();rows.push(['keep',...Array(fields.length).fill('existing')]);const before=JSON.stringify(rows[1]);assert.equal((await call(body())).ok,true);assert.equal(JSON.stringify(rows[1]),before)});
test('analytics allowlist excludes form data and tests',()=>{const s=readFileSync('src/voice/leadClient.ts','utf8');assert.match(s,/attribution\(\)\.test/);assert.match(s,/!consent/);assert.doesNotMatch(s.split('properties:')[1].split('}}')[0],/email|company|answer|name:/)});
